PLUGINNAME = threedi_results_analysis

default: compile

compile: external-dependencies/.generated.marker

# .generated.marker is generated by populate.sh to signify completion.
external-dependencies/.generated.marker: constraints.txt external-dependencies/populate.sh
	cd external-dependencies && ./populate.sh

constraints.txt: dependencies.py
	python3 dependencies.py

test: clean compile
	QT_QPA_PLATFORM=offscreen pytest
	# Note: setup.cfg configures the generic options (like --cov) that are
	# passed to pytest.

zip: compile
	@echo
	@echo "---------------------------"
	@echo "Creating plugin zip bundle."
	@echo "---------------------------"
	rm -rf /tmp/$(PLUGINNAME)
	cd /tmp; cp -r $(CURDIR) $(PLUGINNAME)
	rm -rf /tmp/$(PLUGINNAME)/tests
	rm -rf /tmp/$(PLUGINNAME)/.git
	rm -rf /tmp/$(PLUGINNAME)/.github
	rm -rf /tmp/$(PLUGINNAME)/*.zip
	rm -rf /tmp/$(PLUGINNAME)/Dockerfile
	rm -rf /tmp/$(PLUGINNAME)/docker-compose.yml
	rm -rf /tmp/$(PLUGINNAME)/docker-compose.override.yml
	rm -rf /tmp/$(PLUGINNAME)/.dockerignore
	rm -rf /tmp/$(PLUGINNAME)/external-dependencies/h5py
	rm -rf /tmp/$(PLUGINNAME)/external-dependencies/scipy
	rm -rf /tmp/$(PLUGINNAME)/deps
	rm -rf /tmp/$(PLUGINNAME)/__pycache__
	find /tmp/$(PLUGINNAME) -iname "*.pyc" -delete
	cd /tmp; zip -9r $(CURDIR)/$(PLUGINNAME).zip $(PLUGINNAME)

check: constraints.txt
	# Use pip-compile to check whether all dependencies version constraints are met.
	cp constraints.txt requirements.in
	pip-compile --dry-run
	rm requirements.in

package: compile
	# Create a zip package of the plugin named $(PLUGINNAME).zip.
	# This requires use of git (your plugin development directory must be a
	# git repository).
	# To use, pass a valid commit or tag as follows:
	#   make package VERSION=Version_0.3.2
	@echo
	@echo "------------------------------------"
	@echo "Exporting plugin to zip package.	"
	@echo "------------------------------------"
	rm -f $(PLUGINNAME).zip
	git archive --prefix=$(PLUGINNAME)/ -o $(PLUGINNAME).zip $(VERSION)
	echo "Created package: $(PLUGINNAME).zip"

flake8:
	@echo "#### PEP8/pyflakes issues"
	@flake8 . --extend-exclude=deps
	@echo "No issues found."

clean:
	@echo
	@echo "------------------------------------"
	@echo "Deleting dependencies"
	@echo "------------------------------------"
	rm -rf deps
